apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-liquidity-backend
  namespace: us-liquidity
  labels:
    app: us-liquidity-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: us-liquidity-backend
  template:
    metadata:
      labels:
        app: us-liquidity-backend
      annotations:
        consul.hashicorp.com/connect-inject: "false"
    spec:
      serviceAccountName: us-liquidity-backend
      dnsPolicy: ClusterFirst
      containers:
        - name: us-liquidity-backend
          image: registry.registry.svc.cluster.local:5000/us-liquidity-backend:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
              protocol: TCP
          envFrom:
            - configMapRef:
                name: us-liquidity-backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: us-liquidity-secrets
                  key: DB_PASSWORD
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: us-liquidity-secrets
                  key: ADMIN_TOKEN
          readinessProbe:
            httpGet:
              path: /api/meta/health
              port: 3200
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "192Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
      restartPolicy: Always
