apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: seaweedfs-s3-1
  namespace: infra
  labels:
    kubernetes.io/service-name: seaweedfs-s3   # สำคัญ! ผูกกับ Service ผ่าน label นี้
addressType: IPv4
ports:
  - name: s3
    port: 30303
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.1.44
    conditions:
      ready: true