apiVersion: v1
kind: Service
metadata:
  name: jira-due-backend
  namespace: jira-due
spec:
  selector:
    app: jira-due-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
