apiVersion: v1
kind: Service
metadata:
  name: pdf-unlock
  namespace: infra
spec:
  selector:
    app: pdf-unlock
  ports:
  - name: metrics
    port: 443
    targetPort: 443 
    protocol: TCP
  type: ClusterIP