apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-bot-config
  namespace: discord-bot
data:
  NODE_ENV: "production"
  N8N_TEST_API: "https://n8n.tarchunk.win/webhook-test/d3b132c4-8380-4b0d-96a6-ea11d2f040a9"
  N8N_PRODUCTION_API: "http://n8n.n8n.svc.cluster.local:443/webhook/d3b132c4-8380-4b0d-96a6-ea11d2f040a9"